name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg

          # Options
          user: timedegree
          template: classic
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
#           plugin_languages_recent_days: 14
#           plugin_languages_recent_load: 300
#           plugin_languages_threshold: 0%
          plugin_languages_ignored: html, css
          plugin_languages_details: lines, percentage
#           plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          commits_authoring: 942734208@qq.com,TimeDegree,Shi_Du,timedegree1@outlook.com
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_rss: yes
          plugin_rss_source: https://blog.tonycrane.cc/atom.xml
          plugin_rss_limit: 3
          config_order: followup, languages, topics, rss


      
      - name: right
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg

          # Options
          plugin_achievements: yes
          #plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_rss: yes
          plugin_rss_source: https://www.timedegree.cn/atom.xml
          plugin_rss_limit: 3
