name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg

          user: timedegree
          template: classic
          base: header 
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          #plugin_languages_ignored: html, css, TeX, CMake
          #plugin_languages_threshold: 2%
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          commits_authoring: TimeDegree,Shi_Du,942734208@qq.com,timedegree1@outlook.com
          plugin_rss: yes
          plugin_rss_source: https://blog.timedegree.cc/atom.xml
          plugin_rss_limit: 3
          plugin_code: yes
          plugin_code_languages: c++, python
          plugin_code_load: 400
          config_order: base.header,languages,rss,code
      
      - name: right
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg
          
          user: timedegree
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
