name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg

          # Options
          user: timedegree
          template: classic
          base: header
          config_timezone: Asia/ShangHai
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css, TeX, CMake
          plugin_languages_threshold: 2%
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_aliases: 'Jupyter Notebook:Ipynb'
          commits_authoring: Matheart, hnwongaf@connect.ust.hk, waautomationwong@gmail.com
          plugin_code: yes
          plugin_code_languages: c++, python
          plugin_code_load: 400
          config_padding: 0, 8 + 11%
          config_order: base.header, base.activity+community, languages, code

      
      - name: right
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg

          # Options
          plugin_achievements: yes
          #plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_rss: yes
          plugin_rss_source: https://www.timedegree.cn/atom.xml
          plugin_rss_limit: 3
